version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretrootpassword
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_USER=mysql_user
      - MYSQL_DATABASE=mysql_database